name: Revert Last Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Revert latest commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git revert HEAD --no-edit
          git push origin HEAD:${{ github.ref_name }}
